### ISSUE TITLE
Setup error "Failed to exchange oauth code into token"

### ISSUE THREAD

**Issue by tommylenz** [mattermost/mattermost-plugin-gitlab#386]
Hi all, trying to link my GitLab account to Mattermost, the following error occurs:

> There was an error connecting to your GitLab: `Failed to exchange oauth code into token: Post "https://gitlab.domain.com/oauth/token": dial tcp 172.22.0.4:443: connect: connection refused` Please double check your configuration.

Our setup is mattermost and gitlab both running via docker on the same server with their repsective subdomains.
I have googled a bit and found others running into the same issue with this setup, yet I didn't find a solution that would work for me. It seems to be about the two services communicating and some proxy issue. Are you aware, and if so, is there a fix? As I think this is a fairly standard setup, at least among startups, it could be added in some sort of FAQ or Known Problems section in the README imo. Any help is appreciated, thanks!
Yours Tommy

**Comment by mickmister** [comment]
Hi @tommylenz, thanks for reporting this :+1:  Some things come to mind here:

- Is the GitLab server listening on port 433?
- Are you able to shell into the Mattermost container and see if you can use `curl` to successfully contact the GitLab server?
- Can you share more info about your docker setup? Possibly some Docker network configuration you have going between the two containers?

**Comment by tommylenz** [comment]
Hi @mickmister, thanks for taking a look.
- Yes, GitLab is listening on port 433
- Yes, I can curl GitLab from inside the Mattermost container
- This is the `docker ps` output:

| CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES |
| --- | --- | --- | --- | --- | --- | --- |
| a35b8b58f592 | mattermost/platform | "/bin/sh -c ./docker…" | 4 days ago | Up 4 days | 3306/tcp, 33060/tcp, 0.0.0.0:8065->8065/tcp, :::8065->8065/tcp | mattermost |
| 21a2e0a5c16f | nginxproxy/acme-companion | "/bin/bash /app/entr…" | 2 months ago | Up 8 days | - | nginx-proxy-ssl |
| 4b81071bc747 | nginxproxy/nginx-proxy | "/app/docker-entrypo…" | 2 months ago | Up 8 days | 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp | nginx-proxy |
| 706ce14586d1 | gitlab/gitlab-ce:latest | "/assets/wrapper" | 2 months ago | Up 8 days (healthy) | 80/tcp, 443/tcp, 0.0.0.0:5050->5050/tcp, :::5050->5050/tcp, 0.0.0.0:5022->22/tcp, :::5022->22/tcp | gitlab |
| a6919510cb3d | postgres:13-alpine | "docker-entrypoint.s…" | 2 months ago | Up 8 days | 5432/tcp | postgres |
| cadfdc2a3d2a | wordpress-image | "docker-entrypoint.s…" | 2 months ago | Up 2 months | 0.0.0.0:280->80/tcp, :::280->80/tcp | wordpress |
| 8f9ef47ac845 | wordpress-db-image | "docker-entrypoint.s…" | 2 months ago | Up 2 months | 3306/tcp, 33060/tcp | db |

- `docker-compose.yml`:
```yml
version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-ssl
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: my-colleague@domain.com
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.domain.com'
    container_name: gitlab
    environment:
      VIRTUAL_HOST: gitlab.domain.com
      LETSENCRYPT_HOST: gitlab.domain.com
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.domain.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 5022
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '5050:5050'
      - '5022:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
    environment:
      # timezone inside container
      TZ: "Europe/Berlin"

      # necessary Postgres options/variables
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "XXXXXXXXXXXXXXXXXX"
      POSTGRES_DB: "postgres"
  mattermost:
    depends_on:
      - postgres
    image: mattermost/platform
    restart: always
    container_name: mattermost
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    volumes:
      - /srv/mattermost/config:/mattermost/config:rw
      - /srv/mattermost/data:/mattermost/data:rw
      - /srv/mattermost/logs:/mattermost/logs:rw
      - /srv/mattermost/plugins:/mattermost/plugins:rw
      - /srv/mattermost/client/plugins:/mattermost/client/plugins:rw
      - /srv/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # timezone inside container
      TZ: "Europe/Berlin"

      # necessary Mattermost options/variables (see env.example)
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://postgres:uRJ7oixxG8xPkntLgHGwkbz3tLfFjWGs@postgres:5432/postgres?sslmode=disable&connect_timeout=10"

      # necessary for bleve
      MM_BLEVESETTINGS_INDEXDIR: "/mattermost/bleve-indexes"

      # Activate Local Mode
      MM_SERVICESETTINGS_ENABLELOCALMODE: true

      # additional settings
      MM_SERVICESETTINGS_SITEURL: "https://mattermost.domain.com"
      VIRTUAL_HOST: mattermost.domain.com
      LETSENCRYPT_HOST: mattermost.domain.com
      VIRTUAL_PORT: 8065
    ports:
      - "8065:8065"
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
```
